CRM/urls.py
from django.contrib import admin
from django.urls import path

from web01.views import views,bas,cus,sale,leads

urlpatterns = [
    path('admin/', admin.site.urls),

    path('index', views.index),
    path('main', views.main),

    path('', bas.depart_list),

    path('about/', views.about),



    #登录
    path('login/', views.login),
    path('logout/', views.logout),
    path('image/code/', views.image_code),

    ##################基础信息#######################

    #部门管理
    path('depart/list/', bas.depart_list),
    path('depart/add/', bas.depart_add),
    path('depart/edit/', bas.depart_edit),
    path('depart/delete/', bas.depart_delete),
    path('depart/detail/', bas.depart_detail),


    #管理员管理
    path('admins/list/', bas.admin_list),
    path('admins/add/', bas.admin_add),
    path('admins/edit/', bas.admin_edit),
    path('admins/delete/', bas.admin_delete),
    path('admins/detail/', bas.admin_detail),



    ##员工管理
    path('employee/list/', bas.employee_list),
    path('employee/add/', bas.employee_add),
    path('employee/edit/', bas.employee_edit),
    path('employee/delete/', bas.employee_delete),
    path('employee/detail/', bas.employee_detail),



    #产品管理
    path('product/list/', bas.product_list),
    path('product/add/', bas.product_add),
    path('product/edit/', bas.product_edit),
    path('product/delete/', bas.product_delete),
    path('product/detail/', bas.product_detail),




    #客户管理
    path('customer/list/', cus.customer_list),
    path('customer/add/', cus.customer_add),
    path('customer/edit/', cus.customer_edit),
    path('customer/delete/', cus.customer_delete),
    path('customer/detail/', cus.customer_detail),



    #订单管理
    path('order/list/', sale.order_list),
    path('order/add/', sale.order_add),
    path('order/edit/', sale.order_edit),
    path('order/delete/', sale.order_delete),

    path('order/detail/', sale.order_detail),


    #公司管理
    path('company/list/', bas.company_list),
    path('company/add/', bas.company_add),
    path('company/edit/', bas.company_edit),
    path('company/delete/', bas.company_delete),
    path('company/detail/', bas.company_detail),


    #财务管理
    #订单应收
    path('order/receivable/', sale.order_receivable_list),
    path('order/payment/', sale.order_receivable),
    path('order/rec/detail/', sale.ord_rec_detail),


    #线索管理
    path('lead/list/', leads.lead_list),
    path('lead/add/', leads.lead_add),
    path('lead/edit/', leads.lead_edit),
    path('lead/delete/', leads.lead_delete),
    path('lead/detail/', leads.lead_detail),


    #我的客户
    path('my/customer/', cus.my_customer_list),
    path('my/customer/add/', cus.my_customer_add),
    path('my/customer/edit/', cus.my_customer_edit),
    path('my/customer/delete/', cus.my_customer_delete),

    path('my/customer/detail/', cus.my_customer_detail),


    #跟进记录
    path('follow/list/', cus.follow_list),
    path('follow/add/', cus.follow_add),
    # path('follow/edit/', cus.follow_edit),
    path('follow/delete/', cus.follow_delete),
    # path('follow/detail/', cus.follow_detail),

]

web01/models.py
from random import choice

from django.db import models
from django.db.models import SmallIntegerField


# Create your models here.

class Department(models.Model):
    """部门表"""
    title = models.CharField(max_length=100,verbose_name='部门')

    def __str__(self):
        return self.title


class Admin(models.Model):
    """管理员表"""
    name = models.CharField(max_length=32, verbose_name='管理员姓名')
    password = models.CharField(max_length=64, verbose_name='密码')

    gender_choices = (
        (1, '男'),
        (2, '女'),
    )
    gender = SmallIntegerField(choices=gender_choices, verbose_name='性别', default=1)
    email = models.EmailField(verbose_name='邮箱', blank=True, null=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, verbose_name='部门')



    def __str__(self):
        return self.name




class Employee(models.Model):
    """员工表"""

    gender_choices = (
        (1, '男'),
        (2, '女'),
    )
    name = models.CharField(max_length=100)
    gender = SmallIntegerField(choices=gender_choices,verbose_name='性别',default=1)
    email = models.EmailField(verbose_name='邮箱')
    department = models.ForeignKey(Department, on_delete=models.CASCADE,verbose_name='部门')

    def __str__(self):
        return self.name

class Product(models.Model):
    """产品表"""
    name = models.CharField(max_length=100,verbose_name='产品名称')
    count = models.PositiveIntegerField(verbose_name='库存')
    description = models.TextField(verbose_name='产品描述',blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='价格')

    def __str__(self):
        return self.name

class Lead(models.Model):
    """线索"""
    name = models.CharField(max_length=100)
    status = models.CharField(max_length=50)
    assigned_to = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True, blank=True,verbose_name='负责人')

class Customer(models.Model):
    """客户"""
    name = models.CharField(max_length=100,verbose_name='客户名称')
    gender_choices = (
        (0, '男'),
        (1, '女'),
    )
    gender = models.SmallIntegerField(verbose_name='性别',choices=gender_choices,default=0)
    company =  models.ForeignKey('Company', on_delete=models.CASCADE,verbose_name='公司',default=1)
    assigned_to = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True, blank=True,verbose_name='负责人')
    phone = models.CharField(max_length=20,verbose_name='电话',blank=True, null=True)
    email = models.EmailField(verbose_name='邮箱',blank=True, null=True)
    status_choice  = (
        (0, '未分配'),
        (1, '已分配'),
    )
    status = models.SmallIntegerField(choices=status_choice,verbose_name='状态',default=0)
    created_at = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')


    def __str__(self):
        return self.name



class Order(models.Model):
    """订单"""

    oid = models.CharField(max_length=100,verbose_name='订单号')
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE,verbose_name='客户')
    product = models.ForeignKey(Product, on_delete=models.CASCADE,verbose_name='产品')
    quantity = models.PositiveIntegerField(verbose_name='数量')
    total_price = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='总价')
    paid = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='已付金额',default=0)

    status_choices = (
        (0, '已完成'),
        (1, '未完成'),
    )

    status = models.SmallIntegerField(choices=status_choices,verbose_name='状态',default=1)
    created_at = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')
    updated_at = models.DateTimeField(auto_now=True,verbose_name='更新时间')
    admin = models.ForeignKey(Admin, on_delete=models.CASCADE,verbose_name='管理员',default=3)

    def __str__(self):
        return self.oid


class FollowUpRecord(models.Model):
    """跟进记录"""
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE,verbose_name='客户')
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE,verbose_name='负责人')
    notes = models.TextField(verbose_name='备注')
    created_at = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')

class FinancialRecord(models.Model):
    """财务记录"""
    order = models.ForeignKey(Order, on_delete=models.CASCADE,verbose_name='订单')
    amount_due = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='应付金额')
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='已付金额')
    status = models.CharField(max_length=50,verbose_name='状态')
    created_at = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')
    updated_at = models.DateTimeField(auto_now=True,verbose_name='更新时间')



class Company(models.Model):
    """公司"""
    name = models.CharField(max_length=100,verbose_name='公司名称')
    address = models.CharField(max_length=255,verbose_name='地址')
    phone = models.CharField(max_length=20,verbose_name='电话')
    email = models.EmailField(verbose_name='邮箱',blank=True, null=True)
    website = models.URLField(blank=True, null=True,verbose_name='网站',)
    created_at = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')
    updated_at = models.DateTimeField(auto_now=True,verbose_name='更新时间')

    def __str__(self):
        return self.name

web01/views/cus.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from web01.utils.pagination import Pagination
from web01 import models
from django import forms
from web01.utils.encrypt import md5
from django.views.decorators.csrf import csrf_exempt


class CustomerModelForm(forms.ModelForm):
    class Meta:
        model = models.Customer
        fields = "__all__"


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})


class FollowModelForm(forms.ModelForm):
    class Meta:
        model = models.FollowUpRecord
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})


def customer_list(request):
    # 客户列表
    queryset = models.Customer.objects.filter(status = 1).order_by('id')
    form = CustomerModelForm()
    page_obj = Pagination(request, queryset)

    context = {
        'form': form,
        'queryset': page_obj.page_queryset,
        'page_string': page_obj.html(),
    }

    return render(request, 'customer_list.html', context)


@csrf_exempt
def customer_add(request):
    # 添加客户
    form = CustomerModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'error': form.errors})


@csrf_exempt
def customer_edit(request):
    """编辑"""
    uid = request.GET.get('uid')
    print("接受到的uid", uid)
    row_obj = models.Customer.objects.filter(id=uid).first()
    if not row_obj:
        return JsonResponse({'status': False, 'tips': '数据不存在'})
    form = CustomerModelForm(instance=row_obj, data=request.POST)

    print("有数据")
    if form.is_valid():
        form.save()
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'error': form.errors})


@csrf_exempt
def customer_delete(request):
    """删除客户"""
    uid = request.GET.get('uid')
    models.Customer.objects.filter(id=uid).delete()
    return JsonResponse({'status': True})


@csrf_exempt
def customer_detail(request):
    """客户详情"""
    uid = request.GET.get('uid')
    obj_dict = models.Customer.objects.filter(id=uid).values("name", "assigned_to","gender","company").first()

    return JsonResponse({'status': True, 'data': obj_dict})



#####################我的客户#######################

def my_customer_list(request):
    """我的客户"""

    assign_to = request.session.get('info').get('id')
    queryset = models.Customer.objects.filter(status=1, assigned_to=assign_to).order_by('id')
    form = CustomerModelForm()
    page_obj = Pagination(request, queryset)
    form_f = FollowModelForm()

    context = {
        'form': form,
        'form_f': form_f,
        'queryset': page_obj.page_queryset,
        'page_string': page_obj.html(),
    }

    return render(request, 'my_customer_list.html', context)


@csrf_exempt
def my_customer_add(request):
    """添加我的客户"""
    form = CustomerModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'error': form.errors})


@csrf_exempt
def my_customer_edit(request):
    """编辑我的客户"""
    uid = request.GET.get('uid')
    row_obj = models.Customer.objects.filter(id=uid).first()
    if not row_obj:
        return JsonResponse({'status': False, 'tips': '数据不存在'})
    form = CustomerModelForm(instance=row_obj, data=request.POST)

    if form.is_valid():
        form.save()
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'error': form.errors})


@csrf_exempt
def my_customer_delete(request):
    """删除我的客户"""
    uid = request.GET.get('uid')
    models.Customer.objects.filter(id=uid).delete()
    return JsonResponse({'status': True})


@csrf_exempt
def my_customer_detail(request):
    """我的客户详情"""
    uid = request.GET.get('uid')
    obj_dict = models.Customer.objects.filter(id=uid).values("name", "assigned_to")
    return JsonResponse({'status': True, 'data': obj_dict})


##########跟进客户############


@csrf_exempt
def follow_add(request):
    """新建跟进记录"""
    form = FollowModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'error': form.errors})


def follow_list(request):
    """跟进记录"""
    queryset = models.FollowUpRecord.objects.all().order_by('id')
    page_obj = Pagination(request, queryset)
    form = FollowModelForm()

    context = {
        'form': form,
        'queryset': page_obj.page_queryset,
        'page_string': page_obj.html(),
    }

    return render(request, 'follow_list.html', context)

def follow_delete(request):
    """删除跟进记录"""
    uid = request.GET.get('uid')
    models.FollowUpRecord.objects.filter(id=uid).delete()
    return JsonResponse({'status': True})

web01/views/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django import forms
from django.http import HttpResponse
from web01 import models
from io import BytesIO


from web01.utils.encrypt import md5
from web01.utils.code import check_code



# Create your views here.

def index(request):
    return HttpResponse("Hello, world. You're at the CRM index.")




def main(request):
    return render(request, 'main.html')


class LoginForm(forms.Form):
    name = forms.CharField(
        label='用户名',
        widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    password = forms.CharField(
        label='密码',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    code = forms.CharField(
        label= '验证码',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True
    )

    def clean_password(self):
        pwd = self.cleaned_data.get('password')
        return md5(pwd)



##登录
def login(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    form = LoginForm(data=request.POST)
    if form.is_valid():
        #clean_data = form.cleaned_data
        #clean_data['password'] = md5(clean_data['password'])

        # 验证码的校验
        user_input_code = form.cleaned_data.pop('code')
        code = request.session.get('image_code', "")
        if code.upper() != user_input_code.upper():
            form.add_error('code', '验证码错误')
            return render(request, 'login.html', {'form': form})

        # 校验
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error('name', '用户名或密码错误')
            return render(request, 'login.html', {'form': form})

        # 正确
        # 网站生成随机字符串；写入到用户浏览器cookie中，再写入到session中
        request.session['info'] = {'id': admin_object.id, 'name': admin_object.name}
        request.session.set_expiry(60 * 60 * 24 * 14)
        return redirect('/admins/list/')

    return render(request, 'login.html', {'form': form})

def image_code(request):
    """生成图片验证码"""

    img, code_string = check_code()

    # 写入到自己的session中，以便于后续获取验证码
    request.session['image_code'] = code_string
    # 给验证码设置过期时间
    request.session.set_expiry(60)

    # 写入内存
    stream = BytesIO()
    img.save(stream, 'png')
    stream.getvalue()

    return HttpResponse(stream.getvalue())

def logout(request):
    """注销"""
    request.session.clear()
    return redirect('/login/')

def about(request):
    return render(request, 'about.html')

web01/templates/change.html
{% extends 'layout.html' %}




{% block content %}


    <div>
        <div class="container">
            <div class="card" style="width: 58rem;">
                <h3 class="card-title" style="margin-left: 2rem">{{ title }}</h3>
                <div class="card-body">
                    <form method="post" >
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="mb-3">


                            <label> {{ field.label }}:</label>
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        {% endfor %}


                        </div>


                        <input type="submit" class="btn btn-primary" value="提交">
                    </form>
                </div>
            </div>
        </div>
    </div>








{% endblock %}

web01/templates/employee_list.html
{% extends 'layout.html' %}

{% block content %}

    <div>
        <div class="container mt-5">

            <div>
                <div class="card" >
                    <div class="d-flex justify-content-between align-items-center" style="padding: 10px;">
                        <div style="width: 200px">
                            <h2 class="mt-2 " style="margin-left: 10px;">员工管理</h2>
                        </div>

                    </div>

                    <div class="card-body">
                        <a href="#" id="btnAdd" class="btn btn-primary">添加员工</a>
                        <table class="table table-bordered mt-3">
                            <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">姓名</th>
                                <th scope="col">性别</th>
                                <th scope="col">邮箱</th>
                                <th scope="col">部门</th>
                                <th scope="col">操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in queryset %}

                                <tr uid = {{ item.id }}>

                                    <th scope="row">{{ item.id }}</th>
                                    <td> {{ item.name }}</td>
                                    <td> {{ item.get_gender_display }}</td>
                                    <td> {{ item.email }}</td>
                                    <td> {{ item.department }}</td>


                                    <td>
                                        <input uid = "{{ item.id }}" type="button" class="btn btn-primary btn-xs btn-edit" href="" value="编辑">
                                        <input uid = "{{ item.id }}" type="button" class="btn btn-danger btn-xs btn-delete" href="" value="删除">


                                    </td>


                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>


                    </div>

                    <ul class="pagination mt-2">
                        {{ page_string }}
                    </ul>
                </div>
            </div>


            {#            模态框#}
            <div class="modal fade" id="myModel" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="myModalLabel">添加员工</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">

                            <form id="formAdd">
                                <div class="row">
                                    {% for field in form %}
                                        <div class="col-xs-6 col-md-6">
                                            <div class="form-group " style="position: relative">
                                                <label>{{ field.label }}:</label>
                                                {{ field }}
                                                <span class="error-msg"
                                                      style="color: red;position: absolute">{{ field.errors.0 }}</span>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取 消</button>
                            <button id="btnSave" type="button" class="btn btn-primary">保 存</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>



    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="alert alert-danger" role="alert">
                    <h3> A simple danger alert—check it out!</h3>

                    <p style="text-align: right">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取 消</button>
                        <button id='btnConfirmDelete' type="button" class="btn btn-primary">保 存</button>
                    </p>
                </div>

            </div>
        </div>
    </div>


{% endblock %}


{% block js %}

    <script>

        var DELETE_ID;
        var EDIT_ID;


        $(function () {
            bindBtnAddEvent();
            bindBtnSaveEvent();
            bindBtnDeleteEvent();
            bindBtnConfirmDeleteEvent();
            bindBtnEditEvent();

        })

        function bindBtnAddEvent() {
            $('#btnAdd').click(function () {

                EDIT_ID = null;
                //清空表单
                $('#formAdd')[0].reset();


                $('#myModel').modal('show');
            })
        }

        function bindBtnSaveEvent() {
            $("#btnSave").click(function () {

                //清除错误信息
                $(".error-msg").empty();

                if (EDIT_ID) {
                    //编辑
                    doEdit();

                } else {
                    //新建
                    doAdd();
                }


            });
        }

        function doAdd() {
            $.ajax({
                url: '/employee/add/',
                type: 'post',
                data: $("#formAdd").serialize(),
                dataType: 'JSON',
                success: function (res) {
                    if (res.status) {
                        alert('添加成功');
                        //清空表单
                        $('#formAdd')[0].reset();
                        //关闭对话框
                        $('#myModel').modal('hide');
                        //刷新页面
                        location.reload();

                    } else {
                        $.each(res.error, function (name, erroList) {
                            $("#id_" + name).next().text(erroList[0]);
                        })
                    }
                }
            })
        }

        function doEdit(){
                 $.ajax({
                    url: '/employee/edit/?uid=' + EDIT_ID,
                    type: 'post',
                    data: $("#formAdd").serialize(),
                    dataType: 'JSON',
                    success: function (data) {
                        if (data.status) {
                            alert('提交成功');
                            //清空表单
                            //$("#formAdd")是jQuery对象， -> $("#formAdd")[0]是原生DOM对象
                            $("#formAdd")[0].reset();
                            //关闭对话框
                            $('#myModal').modal('hide');
                            //刷新页面
                            location.reload();

                        } else {
                            if(data.tips){
                                alert(data.tips);
                            }
                            //显示错误信息
                            $.each(data.error, function (name, erroList) {
                                $("#id_" + name).next().html(erroList[0]);
                            })
                        }

                        console.log(data);

                        {#//提交成功后，关闭对话框#}
                        {#$('#myModal').modal('hide');#}
                        {#//刷新页面#}
                        {#location.reload();#}
                    }
                })
        }

            function bindBtnDeleteEvent() {
            //给删除按钮绑定事件
            $(".btn-delete").click(function () {
                //显示删除对话框
                $('#deleteModal').modal('show');

                //获取要删除的ID赋值给全局变量
                DELETE_ID = DELETE_ID = $(this).attr("uid");


            });
        }

        function bindBtnConfirmDeleteEvent() {
            //给确认删除按钮绑定事件
            $("#btnConfirmDelete").click(function () {
                console.log("测试")
                //点击确认删除按钮后，提交删除请求
                $.ajax({
                    url: '/employee/delete/',
                    type: 'GET',
                    data: {uid: DELETE_ID},
                    dataType: 'JSON',
                    success: function (data) {
                        if (data.status) {
                            alert('删除成功');
                            //关闭对话框
                            $('#deleteModal').modal('hide');
                            //删除页面中的数据
                            $("tr[uid=" + DELETE_ID + "]").remove();
                        } else {
                            alert('删除失败');
                        }
                    }
                })
            });
        }

         function bindBtnEditEvent() {
            $(".btn-edit").click(function () {
                //清空表单
                $("#formAdd")[0].reset();
                EDIT_ID = $(this).attr("uid");


                //发送ajax去后台获取当前行数据
                $.ajax({
                    url: '/employee/detail/',
                    type: 'GET',
                    data: {uid: $(this).attr("uid")},
                    dataType: 'JSON',
                    success: function (data) {
                        //将数据赋值到标签
                        $.each(data.data, function (name, value) {
                            $("#id_" + name).val(value);
                        })


                        //修改对话框的标题
                        $("#myModalLabel").text("修改管理员信息");

                        //点击编辑显示模态框
                        $('#myModel').modal('show');
                    }
                })

                //在对话框显示

            });
        }

    </script>

{% endblock %}

web01/templates/login.html
{% load  static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-5.3.0/css/bootstrap.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #ccc;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            text-align: center;
            margin-bottom: 20px;
        }
    </style>

</head>
<body>
<div class="account">
    <h2>用户登陆</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.name }}
            <span style="color: #842029">{{ form.name.errors.0 }}</span>

        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span>{{ form.password.errors.0 }}</span>

             <div class="form-group">
            <label for="id_code">图片验证码</label>
            <div class="d-flex">
                <div class="flex-grow-1">
                    {{ form.code }}
                    <span>{{ form.code.errors.0 }}</span>
                </div>
                <div class="ml-3">
                    <img id="image_code" src="/image/code/" alt="验证码" style="width: 125px">
                </div>
            </div>
        </div>

            <input type="submit" value="登录" class="btn btn-primary mt-2">
        </div>

    </form>
</div>

</body>
</html>

web01/templates/main.html
{% extends 'layout.html' %}


{% block content %}



        <div class="card-body">

            <h3 >表格</h3>
        </div>



{% endblock %}